[package]
name = "Wordio"
version = "0.0.1"

[build]
target = "index.html"

[[proxy]]
rewrite = "/backend"
backend = "http://localhost:3000"
#For queries
# [[proxy]]
# backend = ""
# For web-sys p2p apps.